version: "3"
networks:
  lavatech:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 111.112.113.0/24


servives:
  web1: 
  build:
    context: .
  tty: "true"
  stdin_open: "true"
  ports:
    - 80:80
  networks:
    - lavatech
  command: bash
